language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r project-web * # 현재 위치의 모든 파일을 해당이름으로 압축한다.
  - mkdir -p deploy #deploy 디렉토리 생성.
  - mv project-web.zip deploy/project-web.zip #파일을 deploy 디렉토리 아래로 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: project-test-sping # S3 버킷 이름 넣기
    region: ap-northeast-2 # s3 버킷 생성한 리전
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # deploy하기 전에 미리 생성한 디렉토리를 저장
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: project-test-sping # S3 버킷
    key: project-web.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: project-test # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: project-test-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true


# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - minjo3988@gmail.com